branches:
  only:
  - master
language: node_js
node_js:
- '8'
before_script:
- npm install
script:
- "./index.js nse-daily-update"
after_success:
- "./push.sh"
env:
  global:
  - secure: ScT7LyhKY4bNnj3Lh7EC0hDYz8K+6hutQmav2svR3dJGBFctcFF9osGM9OrktyZxxEXb2xPf76q2W3mYYAg53a3xhXe2Cmdvetdr4Y9ZOlX3mm0TAIPxRA4GywYlxYEh/rcS8AMGnr9uMmS03X6szo0RMykmMHwlREA22aaT2SExiVq7Thj6etprh5SQAVA+qvujlC6KhOFMuBK+8XEiM1JtKh1nrzHgrYrvLZrqM7VeosTttxXfWFgWkn6FQ1oI0zG3BSr/KboEdWXcA6vPBw2//CTqFdb4Ov4s2sD9XKz0P6GJME03mIyNzp3s6nCpPKF/fMH298BF4bdVFXsXlJf6PFSzWHypaaOaVd8frVn9bYqyNBx48Vi8V684mWZp/DbDjIZWf2Zm846RJJiE3AIz55bukEC+Z8rDfkc3s5uT5RSvR8T3xt0HpYaKsTsGiqQWarCOVejAlb/SF1PxoWnGhB982UALQOsxoISjg72RuVWIORQNNwE4v8ZDI//yW6PXZJaW+3h9h0kVSAzHpPDxBDkUEQD5iKAQVExe55ErawVal7kVg2YoxOy+t+cGRprcMrc0gXBKPvX3loTDRDuYNkpPhJhhq3f8K0dtb+6Ad1ypkXl735UI2py4W1CNWUfH4N+Nweip5xBRuY7AjajW8UOa7B3/c7trOLJhcQg=
